@startuml
title Principal action diagram of instrument normalization
start
:Accept message;
if (Instrument exists?) then (no)
    :Shelve message;
    :Lookup instrument;
    if (Instrument is found?) then (no)
        :Notify about missing instrument;
        STOP
    else (yes)
        :Unshelve message; 
    endif 
else (yes)    
endif
:Normalize incoming message;
STOP
@enduml