version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE: LogAppendTime
#  storage:
#    image: openzipkin/zipkin-elasticsearch7
#    container_name: elasticsearch
#    ports:
#      - 9200:9200
#
#  zipkin:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    environment:
#      - STORAGE_TYPE:elasticsearch
#      - "ES_HOSTS=elasticsearch:9300"
#    ports:
#      - 9411:9411
#    depends_on:
#      - storage
#
#  dependencies:
#    image: openzipkin/zipkin-dependencies
#    container_name: dependencies
#    entrypoint: crond -f
#    depends_on:
#      - storage
#    environment:
#      - STORAGE_TYPE=elasticsearch
#      - "ES_HOSTS=elasticsearch:9300"
#      - "ES_NODES_WAN_ONLY=true"