@startuml

title Router sequence diagram

box "Instrument normalizer"
participant Router order 10
end box
participant TEE order 50 
participant Downstreams order 50 


-> Router : onReceive({message + instrumentData})
activate Router
Router -> Router : normalize(instrumentData, message)
Router -> TEE : getRoute(message)
activate TEE
TEE -> Router : topicName
deactivate TEE
Router -> Downstreams : publish(topicName, message)
deactivate Router
@enduml

