@startuml

title Seeker sequence diagram

box "Instrument normalizer"
participant Reducer order 20 
participant Seeker order 30 
participant Receiver order 40
end box
participant ExternalStaticProvider order 50 


Reducer -> Seeker : onReceive(lookupRequest)
activate Seeker
Seeker -> ExternalStaticProvider : lookups()
activate ExternalStaticProvider
ExternalStaticProvider -> Seeker: Response
deactivate ExternalStaticProvider
Seeker -> Receiver : publish(LookupResponse)
deactivate Seeker

@enduml
