@startuml

title Receiver sequence diagram


collections KafkaConnect order 10
box "Instrument normalizer"
participant Seeker order 15
participant Receiver order 20 
collections Downstreams order 30 
participant Reducer order 35 
end box
database InstrumentKeeper order 50
participant DLQ order 55

== Direct flow ==
KafkaConnect -> Receiver: onReceive(normalizeInstrument)
activate Receiver
Receiver -> InstrumentKeeper : lookupInstrumentID(normalizeInstrument.securityId)
activate InstrumentKeeper
InstrumentKeeper -> Receiver : instrumentId
deactivate InstrumentKeeper
alt#Gold #LightBlue instrumentId is not null
Receiver -> Receiver: mutate(originalMessage, instrumentId)
Receiver -> Downstreams: publish(originalMessage, normalizeInstrument.egressTopic)
else #Pink else
Receiver -> Receiver: shelveNormalizeInstrument(normalizeInstrument.securityId, normalizeInstrument)
Receiver -> Reducer: publish(lookupInstrument)
end
deactivate Receiver
== Lookup flow ==
Seeker -> Receiver: onReceive(lookupResponse)
activate Receiver
alt#Gold #LightBlue is lookup successful 
Receiver -> Receiver: List<normalizeInstrument> unshelve(lookupResponse.securityId)
Receiver -> Downstreams: publish(originalMessage, normalizeInstrument.egressTopic)
Receiver -> InstrumentKeeper: upsert(lookupResponse.instrumentData)
else #Pink else
Receiver -> DLQ: publish(InstrumentLookupFailed)
end
@enduml
