@startuml

title Reducer sequence diagram


box "Instrument normalizer"
participant Receiver order 20 
participant Reducer order 30 
participant Seeker order 40 
end box
== Processing ==
Receiver -> Reducer : onReceive(securityId, byte[])
activate Reducer
Reducer -> Reducer : getStoredSecurity(securityId)
alt#Gold #LightBlue Last security request was sent more than THROTTLE_TIME
Reducer -> Seeker : publish(byte[])  
Reducer -> Reducer : upsertSecurityIdLastUsage(securityId)
end
deactivate Reducer
== Scheduling ==
Reducer -> Reducer : getThrottledSecurityIds()
activate Reducer
Reducer -> Reducer : cleanUp(lastUsage > THROTTLE_TIME)
deactivate Reducer

@enduml
