spring:
  main.web-application-type: NONE

server.port: 9001
management:
  server.port: 9001
  endpoints.web.exposure.include: "*"

kafka:
  bootstrap:
    servers: localhost:9092

logging.pattern.level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} %5p